# -*- coding: utf-8 -*-
"""Rebuild src/data from Wix _wix-page.html (warmup JSON = canonical order)."""
from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
HTML = (ROOT / "_wix-page.html").read_text(encoding="utf-8")
MEDIA = "https://static.wixstatic.com/media/"
APP_ID = "14271d6f-ba62-d045-549b-ab972ae1f70e"


def parse_warmup() -> dict:
    m = re.search(
        r'<script type="application/json" id="wix-warmup-data">(.+?)</script>',
        HTML,
        re.DOTALL,
    )
    if not m:
        raise SystemExit("missing wix-warmup-data")
    return json.loads(m.group(1))


def gallery_items(data: dict, key: str) -> list[dict]:
    g = data.get("appsWarmupData", {}).get(APP_ID, {}).get(key)
    if not g:
        return []
    items = sorted(
        g.get("items", []),
        key=lambda x: float(x.get("orderIndex", 0)),
    )
    out = []
    for it in items:
        mu = it.get("mediaUrl") or ""
        url = mu if mu.startswith("http") else MEDIA + mu
        md = it.get("metaData") or {}
        name = (md.get("fileName") or md.get("title") or "").strip()
        out.append({"imageSrc": url, "label": name or "พันธมิตร"})
    return out


def _strip_wix_resize(url: str) -> str:
    """คืน URL ไฟล์ดิบ (ตัด /v1/fill/...) ให้ Next/Image โหลดสม่ำเสมอ"""
    if "/v1/" in url:
        return url.split("/v1/")[0]
    return url


def hero_image_url() -> str | None:
    """รูปฮีโร่จริง = <img id=\"img_comp-lreem4is\" src=\"...\" หลัง SITE_CONTAINER"""
    sc = HTML.find('id="SITE_CONTAINER"')
    if sc < 0:
        return None
    hi = HTML.find("img_comp-lreem4is", sc)
    if hi < 0:
        return None
    sub = HTML[hi : hi + 2000]
    m = re.search(
        r'src="(https://static\.wixstatic\.com/media/[^"]+)"',
        sub,
    )
    if not m:
        return None
    return _strip_wix_resize(m.group(1))


def header_logo_url() -> str | None:
    """โลโก้แถบบน = ไฟล์ 11062b แรกระหว่าง comp-lbahbgm9 กับรูปฮีโร่ (ลำดับ DOM เดียวกับ Wix)"""
    sc = HTML.find('id="SITE_CONTAINER"')
    if sc < 0:
        return None
    vs = HTML.find("comp-lbahbgm9", sc)
    hi = HTML.find("img_comp-lreem4is", sc)
    if vs < 0 or hi < 0 or hi <= vs:
        chunk = HTML[sc : sc + 120_000]
    else:
        chunk = HTML[vs:hi]
    m = re.search(
        r"https://static\.wixstatic\.com/media/11062b_[a-z0-9]+~mv2\.(?:png|jpg|jpeg|webp|svg)",
        chunk,
        re.I,
    )
    if m:
        return _strip_wix_resize(m.group(0))
    m2 = re.search(
        r'(?:uri&quot;:&quot;)(11062b_[a-z0-9]+~mv2\.(?:png|jpg|jpeg|webp|svg))&quot;',
        chunk,
        re.I,
    )
    if m2:
        return MEDIA + m2.group(1)
    return None


def main() -> None:
    data = parse_warmup()
    partners = gallery_items(data, "comp-lcft52f9_galleryData")
    strip = gallery_items(data, "comp-lrpusuya_galleryData")
    hero = hero_image_url()
    logo = header_logo_url()

    ts = [
        "export type HospitalPartner = {",
        "  id: string;",
        "  shortName: string;",
        "  imageSrc: string;",
        "};",
        "",
        "/**",
        " * โลโก้พันธมิตรจาก Wix Pro Gallery `comp-lcft52f9` — เรียงตาม orderIndex ใน warmup JSON",
        " * (SSR ส่งมา 25 รายการจากทั้งหมด totalItemsCount 40 — ที่เหลือโหลดฝั่ง Wix หลัง hydrate)",
        " */",
        "export const hospitalPartners: HospitalPartner[] = [",
    ]
    for i, p in enumerate(partners, start=1):
        lab = p["label"].replace('"', "'").replace("\\", "/")[:100]
        ts.append(
            "  {"
            + f' id: "partner-{i:02d}", shortName: "{lab}", imageSrc: "{p["imageSrc"]}" '
            + "},"
        )
    ts.append("];")
    ts.append("")
    (ROOT / "src" / "data" / "hospitals.ts").write_text("\n".join(ts), encoding="utf-8")

    st = [
        "export type WixStripImage = { imageSrc: string; alt: string };",
        "",
        "/** แถบบน Wix — gallery `comp-lrpusuya` (5 รูป) */",
        "export const wixTopStripImages: WixStripImage[] = [",
    ]
    for p in strip:
        lab = p["label"].replace('"', "'")[:80]
        st.append(f'  {{ imageSrc: "{p["imageSrc"]}", alt: "{lab}" }},')
    st.append("];")
    st.append("")
    (ROOT / "src" / "data" / "wix-strip.ts").write_text("\n".join(st), encoding="utf-8")

    sa = [
        "/** Auto-generated by scripts/sync_wix_assets.py */",
        f"export const WIX_HERO_IMAGE = {json.dumps(hero or '')};",
        f"export const WIX_HEADER_LOGO = {json.dumps(logo or '')};",
        "",
        "/** Main homepage hero (local file under public/images/hero/) */",
        'export const HOME_HERO_IMAGE = "/images/hero/kbba-hero-banner.png";',
        "",
    ]
    (ROOT / "src" / "data" / "site-assets.ts").write_text("\n".join(sa), encoding="utf-8")

    meta = {
        "heroUrl": hero,
        "headerLogoUrl": logo,
        "partnerCount": len(partners),
        "stripCount": len(strip),
    }
    print(json.dumps(meta, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
