/** Auto-generated by scripts/sync_wix_assets.py */
export const WIX_HERO_IMAGE = "https://static.wixstatic.com/media/e22438_3bf8c54e9eeb46c4aee6e6170122757e~mv2.png";

/** Main homepage hero (local asset; square — use object-contain so it is never cropped) */
export const HOME_HERO_IMAGE = "/images/hero/kbba-hero-banner.png";
export const WIX_HEADER_LOGO = "https://static.wixstatic.com/media/11062b_362ef89dec51403eb0ee59a21bde967c~mv2.png";
